name: RP1

on:
  schedule:
    # 04:00 UTC = 05:00 по польскому времени (зимнее время)
    # Запуск каждого 2-го числа месяца
    - cron: '0 4 */2 * *'
  
  workflow_dispatch:
    # Кнопка для ручного запуска

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5  # Обновили до v5

      - name: Set up Python
        uses: actions/setup-python@v6 # Обновлили до v6
        with:
          python-version: '3.11'

      # Декодируем секрет в JSON файл, который ждет скрипт
      - name: Decode Google Credentials
        run: echo "${{ secrets.G_KEYS_BASE64 }}" | base64 --decode > silken-glyph-443313-i4-cdf14b36288a.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright gspread oauth2client pandas
          playwright install chromium --with-deps

      - name: Run Python script
        run: python ranking_scraper_main.py
        env:
          # Пробрасываем путь к файлу в окружение
          GOOGLE_APPLICATION_CREDENTIALS: silken-glyph-443313-i4-cdf14b36288a.json
