name: RP1

on:
  schedule:
    # 04:00 UTC = 05:00 по польскому времени (зимнее время)
    # Запуск каждого 3-го числа месяца
    - cron: '0 4 */3 * *'
  
  workflow_dispatch:
    # Эта строка оставляет кнопку для ручного запуска в любое время

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright gspread oauth2client pandas
          playwright install chromium --with-deps

      - name: Run Python script
        run: python ranking_scraper_main.py
